on:
  push:
    branches:
      - main
    paths:
      - 'bench/micro/**/*'
      - 'src/**/*'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./bench/micro

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # build
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: |
          cd ..
          bun i
          bun task build
          cd micro

          bun i

      # bun
      - name: bun
        continue-on-error: true
        run: bun run.ts bun . md

      # deno
      - uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: latest

      - name: deno
        continue-on-error: true
        run: bun run.ts deno . md

      # node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: node
        continue-on-error: true
        run: bun run.ts node . md

      # Engines
      - name: setup jsvu
        run: |
          bun i jsvu -g
          jsvu --engines=v8,javascriptcore,spidermonkey --os=linux64

      - name: v8
        continue-on-error: true
        run: bun run.ts v8 . md

      - name: jsc
        continue-on-error: true
        run: bun run.ts jsc . md

      - name: spidermonkey
        continue-on-error: true
        run: bun run.ts spidermonkey . md

      - name: llrt
        continue-on-error: true
        run: |
          bun llrt/install.ts v0.8.1-beta
          bun run.ts llrt .

      - name: quickjs
        continue-on-error: true
        run: |
          bun quickjs/install.ts linux x86_64 2026-06-04
          bun run.ts quickjs .

      # Push results
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "update micro-benchmark results"

      - name: Push with retry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..10}; do
            git pull --rebase origin ${{ github.ref_name }}

            if git push origin HEAD:${{ github.ref_name }}; then
              echo "Push succeeded"
              exit 0
            fi

            echo "Push failed, retry $i..."
            sleep 3
          done

          echo "Push failed after retries"
          exit 1
